### ISSUE TITLE
Feature: MSI File support

### ISSUE THREAD

**Issue by fras2560** [Burzo/electron-forge-ssl-code-sign-plugin#4]
> Please note that msi files are currently not supported for signing.

The README says it does not sign msi files. Would it be possible to extend this plugin so it does?

**Comment by Burzo** [comment]
It is possible, yes. However, I'm kind of stuck on other things in life at the moment, and can't dedicate time to this project right now.

PR's are of course welcome.

**Comment by fras2560** [comment]
I ended up just using the Github Action for azure signing and sign every after forge builds the app

https://github.com/azure/trusted-signing-action
